apiVersion: apps/v1
kind: Deployment
metadata:
  name: jootopia-infoconnector-app
  namespace: team-1
spec:
  replicas: 1 #pod 몇개 띄울건가
  selector:
    matchLabels:
      app: jootopia-infoconnector-app
  template:
    metadata:
      labels:
        app: jootopia-infoconnector-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: alpha.eksctl.io/nodegroup-name
                    operator: In
                    values:
                      - ng-1
      containers:
        - name: jootopia-infoconnector-app
          image: 686710509719.dkr.ecr.ap-northeast-2.amazonaws.com/team-1:20231020003825 #
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jootopia-infoconnector-service
  namespace: team-1
spec:
  type: NodePort
  selector:
    app: jootopia-infoconnector-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080