spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#<<<<<<< HEAD
#    url : jdbc:mysql://testdb.cn85ab2rvl73.ap-northeast-2.rds.amazonaws.com:3306/demo?serverTimezone=Asia/Seoul
#=======
    url : jdbc:mysql://localhost:3306/infoConnector?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false #osiv
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        default_batch_fetch_size: 1000

